name: GitHub Pages Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.X
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      - run: npm install yarn -g
      - run: yarn && yarn push:esbuild
